### PR TITLE
feat: add network as a readonly property on a psbt

### PR DESCRIPTION
**Pull request by davidkaplanbitgo**
TICKET: [BG-67822](https://bitgoinc.atlassian.net/browse/BG-67822)

[BG-67822]: https://bitgoinc.atlassian.net/browse/BG-67822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lcovar — APPROVED** [review]

**Comment by brandonblack** [comment]
Why can't we do this up at the utxo-lib level?

**Comment by davidkaplanbitgo** [comment]
> Details

`psbt.opts` is private

**Comment by brandonblack** [comment]
But we could save the network from the opts in the higher level class before passing it down, couldn't we? Unless we're going to _use_ it in here, I'd rather continue to work toward minimizing our diff vs. upstream. Even if it is a bit of a fool's errand at this point :cry:

**Comment by davidkaplanbitgo** [comment]
YAGNI here, going to do it upstream in `utxo-lib`

**Comment by davidkaplanbitgo** [comment]
> But we could save the network from the opts in the higher level class before passing it down, couldn't we? Unless we're going to _use_ it in here, I'd rather continue to work toward minimizing our diff vs. upstream. Even if it is a bit of a fool's errand at this point 😢

tis true - it would be cleaner here but I see what you're saying

**Pull request closed without merging**
